object FrToast: TFrToast
  object flexDemoPage: TUniDSAFlexPanel
    Tag = 120
    Width = 900
    Height = 680
    Align = alClient
    Flex.Direction = fdColumn
    Flex.Wrap = fwNoWrap
    Flex.Gap = 20
    Flex.Padding = 24
    Flex.Overflow = foAuto
    object usbPrincipal: TUniDSAFlexPanel
      Left = 0
      Top = 0
      Width = 624
      Height = 441
      Hint = ''
      TabOrder = 0
      Tag = 110
      Flex.AutoHeight = True
      Flex.Gap = 10
      Flex.AlignContent = faStart
      Flex.Overflow = foVisible
      Flex.Direction = fdColumn
      Flex.Wrap = fwNoWrap
      FlexItem.Shrink = 0
      ParentColor = False
      Color = 16579066
      Align = alNone
      object UniLabel1: TUniLabel
        Left = 20
        Top = 20
        Width = 51
        Height = 30
        Hint = ''
        Caption = 'Toast'
        ParentFont = False
        Font.Height = 30
        Font.Style = [fsBold]
        ParentColor = False
        Color = clBtnFace
        TabOrder = 1
        Align = alNone
      end
      object UniLabel2: TUniLabel
        Left = 20
        Top = 50
        Width = 185
        Height = 20
        Hint = ''
        Caption = 'Componente de notifica'#231#227'o'
        ParentFont = False
        Font.Color = clGray
        Font.Height = -15
        ParentColor = False
        Color = clBtnFace
        TabOrder = 2
        Align = alNone
      end
      object ugbMensagem: TUniDSAFlexPanel
        Left = 20
        Top = 80
        Width = 601
        Height = 70
        Hint = ''
        TabOrder = 0
        Tag = 100
        Flex.AutoHeight = True
        Flex.Gap = 16
        Flex.AlignContent = faStart
        Flex.Overflow = foVisible
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        FlexItem.Shrink = 0
        ParentColor = False
        Color = clWhite
        Flex.Padding = 20
        Align = alNone
        object lblSectionugbMensagem: TUniLabel
          Tag = 100
          Caption = 'Mensagem'
          Height = 28
          Align = alNone
        end
        object UniContainerPanel20: TUniDSAFlexPanel
          Left = 2
          Top = 20
          Width = 597
          Height = 42
          Hint = ''
          TabOrder = 1
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object UniContainerPanel23: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 163
            Height = 39
            Hint = ''
            TabOrder = 1
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel16: TUniLabel
              Left = 0
              Top = 0
              Width = 30
              Height = 13
              Hint = ''
              Caption = 'T'#237'tulo'
              ParentColor = False
              Color = clBtnFace
              TabOrder = 1
              Align = alNone
            end
            object edtTitulo: TUniEdit
              Left = 0
              Top = 17
              Width = 163
              Hint = ''
              Text = 'T'#237'tulo Toast'
              TabOrder = 2
              Align = alNone
            end
          end
          object UniContainerPanel21: TUniDSAFlexPanel
            Left = 172
            Top = 0
            Width = 157
            Height = 39
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel15: TUniLabel
              Left = 0
              Top = 0
              Width = 56
              Height = 13
              Hint = ''
              Caption = 'Mensagem'
              TabOrder = 1
              Align = alNone
            end
            object edtMensagem: TUniEdit
              Left = 0
              Top = 17
              Width = 157
              Hint = ''
              Text = 'Mensagem Toast'
              TabOrder = 2
              Align = alNone
            end
          end
          object UniContainerPanel22: TUniDSAFlexPanel
            Left = 335
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMostrar: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mostrar'
              TabOrder = 1
              OnClick = btnMostrarClick
              Align = alNone
            end
          end
        end
      end
      object UniLabel3: TUniLabel
        Left = 20
        Top = 155
        Width = 251
        Height = 13
        Hint = ''
        Caption = 'Demais recursos ser'#227'o exemplificados em breve...'
        ParentFont = False
        Font.Color = clGray
        Font.Height = -12
        ParentColor = False
        Color = clBtnFace
        TabOrder = 3
        Align = alNone
      end
    end
  end
  object Toast: TUniDSAToast
    Version = '1.1.0'
    Icon = Success
    ShowHideTransition = Fade
    HideAfter = 3000
    AllowToastClose = True
    Stack.Enabled = True
    Stack.Value = 5
    BgColor.Enabled = False
    BgColor.Color = clAqua
    TextColor.Enabled = False
    TextColor.Color = clAqua
    TextAlign = Left
    Position.Position = BottomRight
    Position.Custom.Left = 0
    Position.Custom.Top = 0
    Position.Custom.Right = 0
    Position.Custom.Bottom = 0
    Loader.Enabled = True
    Loader.Background = clAqua
    Left = 392
    Top = 288
  end
end
