object FrMenuLateral: TFrMenuLateral
  Left = 0
  Top = 0
  Width = 758
  Height = 691
  OnCreate = UniFrameCreate
  TabOrder = 0
  object flexDemoPage: TUniDSAFlexPanel
    Tag = 120
    Width = 900
    Height = 680
    Align = alClient
    Flex.Direction = fdColumn
    Flex.Wrap = fwNoWrap
    Flex.Gap = 20
    Flex.Padding = 24
    Flex.Overflow = foAuto
    object usbPrincipal: TUniDSAFlexPanel
      Left = 0
      Top = 0
      Width = 758
      Height = 691
      Hint = ''
      TabOrder = 0
      Tag = 110
      Flex.AutoHeight = True
      Flex.Gap = 10
      Flex.AlignContent = faStart
      Flex.Overflow = foVisible
      Flex.Direction = fdColumn
      Flex.Wrap = fwNoWrap
      FlexItem.Shrink = 0
      ParentColor = False
      Color = 16579066
      Align = alNone
      object lblTitulo: TUniLabel
        Left = 20
        Top = 20
        Width = 129
        Height = 30
        Hint = ''
        Caption = 'Menu Lateral'
        ParentFont = False
        Font.Height = 30
        Font.Style = [fsBold]
        ParentColor = False
        Color = clBtnFace
        TabOrder = 0
        Align = alNone
      end
      object lblSubTitulo: TUniLabel
        Left = 20
        Top = 50
        Width = 287
        Height = 20
        Hint = ''
        Caption = 'Navega'#231#227'o com submenus em v'#225'rios n'#237'veis'
        ParentFont = False
        Font.Color = clGray
        Font.Height = -15
        ParentColor = False
        Color = clBtnFace
        TabOrder = 1
        Align = alNone
      end
      object ugbTema: TUniDSAFlexPanel
        Left = 20
        Top = 80
        Width = 716
        Height = 265
        Hint = ''
        TabOrder = 2
        Tag = 100
        Flex.AutoHeight = True
        Flex.Gap = 16
        Flex.AlignContent = faStart
        Flex.Overflow = foVisible
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        FlexItem.Shrink = 0
        ParentColor = False
        Color = clWhite
        Flex.Padding = 20
        Align = alNone
        object lblSectionugbTema: TUniLabel
          Tag = 100
          Caption = 'Tema'
          Height = 28
          Align = alNone
        end
        object ucpTemaBotoes: TUniDSAFlexPanel
          Left = 2
          Top = 15
          Width = 712
          Height = 38
          Hint = ''
          TabOrder = 1
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object btnTemaAnterior: TUniButton
            Left = 0
            Top = 0
            Width = 29
            Height = 38
            Hint = ''
            Caption = '<'
            TabOrder = 1
            OnClick = btnTemaAnteriorClick
            Align = alNone
          end
          object btnVisualizarTemas: TUniButton
            Left = 34
            Top = 0
            Width = 121
            Height = 38
            Hint = ''
            Caption = 'Iniciar visualiza'#231#227'o'
            TabOrder = 2
            OnClick = btnVisualizarTemasClick
            Align = alNone
          end
          object btnTemaProximo: TUniButton
            Left = 160
            Top = 0
            Width = 29
            Height = 38
            Hint = ''
            Caption = '>'
            TabOrder = 3
            OnClick = btnTemaProximoClick
            Align = alNone
          end
          object btnMenuPesquisa: TUniButton
            Left = 194
            Top = 0
            Width = 121
            Height = 38
            Hint = ''
            Caption = 'Ocultar Pesquisa...'
            TabOrder = 4
            OnClick = btnMenuPesquisaClick
            Align = alNone
          end
          object btnOcultarTema: TUniButton
            Left = 320
            Top = 0
            Width = 121
            Height = 38
            Hint = ''
            Caption = 'Ocultar escolha tema'
            TabOrder = 5
            OnClick = btnOcultarTemaClick
            Align = alNone
          end
          object btnOcultarPerfil: TUniButton
            Left = 446
            Top = 0
            Width = 121
            Height = 38
            Hint = ''
            Caption = 'Ocultar Perfil'
            TabOrder = 6
            OnClick = btnOcultarPerfilClick
            Align = alNone
          end
          object btnOcultarMenu: TUniButton
            Left = 572
            Top = 0
            Width = 121
            Height = 38
            Hint = ''
            Caption = 'Ocultar Menu'
            TabOrder = 7
            OnClick = btnOcultarMenuClick
            Align = alNone
          end
        end
        object UniPanel4: TUniDSAFlexPanel
          Left = 2
          Top = 58
          Width = 712
          Height = 1
          Hint = ''
          TabOrder = 7
          Tag = 102
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdColumn
          Flex.Wrap = fwNoWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Visible = False
          Align = alNone
        end
        object ucpTemaBorda: TUniDSAFlexPanel
          Left = 2
          Top = 64
          Width = 712
          Height = 57
          Hint = ''
          TabOrder = 2
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object b1: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 706
            Height = 14
            Hint = ''
            TabOrder = 1
            Tag = 101
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdRow
            Flex.Wrap = fwWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel11: TUniLabel
              Left = 0
              Top = 0
              Width = 31
              Height = 13
              Hint = ''
              Caption = 'Borda'
              TabOrder = 1
              Align = alNone
            end
          end
          object b2: TUniDSAFlexPanel
            Left = 3
            Top = 17
            Width = 69
            Height = 37
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel3: TUniLabel
              Left = 0
              Top = 0
              Width = 25
              Height = 13
              Hint = ''
              Caption = 'Topo'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuBordaTopo: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 69
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuBordaTopoChange
              Align = alNone
            end
          end
          object b3: TUniDSAFlexPanel
            Left = 78
            Top = 17
            Width = 90
            Height = 37
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel4: TUniLabel
              Left = 0
              Top = 0
              Width = 48
              Height = 13
              Hint = ''
              Caption = 'Esquerda'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuBordaEsquerda: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 90
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuBordaTopoChange
              Align = alNone
            end
          end
          object b4: TUniDSAFlexPanel
            Left = 174
            Top = 17
            Width = 90
            Height = 37
            Hint = ''
            TabOrder = 4
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel5: TUniLabel
              Left = 0
              Top = 0
              Width = 34
              Height = 13
              Hint = ''
              Caption = 'Direita'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuBordaDireita: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 90
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuBordaTopoChange
              Align = alNone
            end
          end
          object b5: TUniDSAFlexPanel
            Left = 270
            Top = 17
            Width = 90
            Height = 37
            Hint = ''
            TabOrder = 5
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel6: TUniLabel
              Left = 0
              Top = 0
              Width = 38
              Height = 13
              Hint = ''
              Caption = 'Inferior'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuBordaInferior: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 90
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuBordaTopoChange
              Align = alNone
            end
          end
        end
        object UniPanel2: TUniDSAFlexPanel
          Left = 2
          Top = 126
          Width = 712
          Height = 1
          Hint = ''
          TabOrder = 5
          Tag = 102
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdColumn
          Flex.Wrap = fwNoWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Visible = False
          Align = alNone
        end
        object ucpTemaArredondamento: TUniDSAFlexPanel
          Left = 2
          Top = 132
          Width = 712
          Height = 57
          Hint = ''
          TabOrder = 3
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object c1: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 706
            Height = 14
            Hint = ''
            TabOrder = 1
            Tag = 101
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdRow
            Flex.Wrap = fwWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel12: TUniLabel
              Left = 0
              Top = 0
              Width = 88
              Height = 13
              Hint = ''
              Caption = 'Arredondamento'
              TabOrder = 1
              Align = alNone
            end
          end
          object c2: TUniDSAFlexPanel
            Left = 3
            Top = 17
            Width = 94
            Height = 37
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel7: TUniLabel
              Left = 0
              Top = 0
              Width = 76
              Height = 13
              Hint = ''
              Caption = 'Topo Esquerda'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuArredondarTopoEsquerda: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 94
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuArredondarTopoEsquerdaChange
              Align = alNone
            end
          end
          object c3: TUniDSAFlexPanel
            Left = 103
            Top = 17
            Width = 114
            Height = 37
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel8: TUniLabel
              Left = 0
              Top = 0
              Width = 62
              Height = 13
              Hint = ''
              Caption = 'Topo Direira'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuArredondarTopoDireita: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 114
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuArredondarTopoDireitaChange
              Align = alNone
            end
          end
          object c4: TUniDSAFlexPanel
            Left = 223
            Top = 17
            Width = 106
            Height = 37
            Hint = ''
            TabOrder = 4
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel9: TUniLabel
              Left = 0
              Top = 0
              Width = 89
              Height = 13
              Hint = ''
              Caption = 'Inferior Esquerda'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuArredondarInferiorEsquerda: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 106
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuArredondarInferiorEsquerdaChange
              Align = alNone
            end
          end
          object c5: TUniDSAFlexPanel
            Left = 335
            Top = 17
            Width = 106
            Height = 37
            Hint = ''
            TabOrder = 5
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel10: TUniLabel
              Left = 0
              Top = 0
              Width = 75
              Height = 13
              Hint = ''
              Caption = 'Inferior Direita'
              TabOrder = 2
              Align = alNone
            end
            object edtMenuArredondarInferiorDireita: TUniSpinEdit
              Left = 0
              Top = 15
              Width = 106
              Hint = ''
              TabOrder = 1
              OnChange = edtMenuArredondarInferiorDireitaChange
              Align = alNone
            end
          end
        end
        object UniPanel3: TUniDSAFlexPanel
          Left = 2
          Top = 194
          Width = 712
          Height = 1
          Hint = ''
          TabOrder = 6
          Tag = 102
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdColumn
          Flex.Wrap = fwNoWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Visible = False
          Align = alNone
        end
        object ucpTemaDescricao: TUniDSAFlexPanel
          Left = 2
          Top = 200
          Width = 712
          Height = 57
          Hint = ''
          TabOrder = 4
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object d1: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 706
            Height = 14
            Hint = ''
            TabOrder = 1
            Tag = 101
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdRow
            Flex.Wrap = fwWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel17: TUniLabel
              Left = 0
              Top = 0
              Width = 98
              Height = 13
              Hint = ''
              Caption = 'Descri'#231#245'es de tema'
              TabOrder = 1
              Align = alNone
            end
          end
          object d2: TUniDSAFlexPanel
            Left = 3
            Top = 17
            Width = 163
            Height = 37
            Hint = ''
            TabOrder = 4
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object lblDescricaoTemaEsquerda: TUniLabel
              Left = 0
              Top = 0
              Width = 48
              Height = 13
              Hint = ''
              Caption = 'Esquerda'
              ParentColor = False
              Color = clBtnFace
              TabOrder = 1
              Align = alNone
            end
            object edtMenuDescricaoTemaEsquerda: TUniEdit
              Left = 0
              Top = 15
              Width = 163
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object d3: TUniDSAFlexPanel
            Left = 172
            Top = 17
            Width = 61
            Height = 37
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMenuDescricaoTemaEsquerda: TUniButton
              Left = 0
              Top = 15
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnMenuDescricaoTemaEsquerdaClick
              Align = alNone
            end
          end
          object d4: TUniDSAFlexPanel
            Left = 239
            Top = 17
            Width = 163
            Height = 37
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel19: TUniLabel
              Left = 0
              Top = 0
              Width = 34
              Height = 13
              Hint = ''
              Caption = 'Direita'
              ParentColor = False
              Color = clBtnFace
              TabOrder = 1
              Align = alNone
            end
            object edtMenuDescricaoTemaDireita: TUniEdit
              Left = 0
              Top = 15
              Width = 163
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object d5: TUniDSAFlexPanel
            Left = 408
            Top = 17
            Width = 61
            Height = 37
            Hint = ''
            TabOrder = 5
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnDescricaoTemaDireita: TUniButton
              Left = 0
              Top = 15
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnDescricaoTemaDireitaClick
              Align = alNone
            end
          end
          object d6: TUniDSAFlexPanel
            Left = 496
            Top = 17
            Width = 88
            Height = 37
            Hint = ''
            TabOrder = 6
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnRedefinirDescricao: TUniButton
              Left = 0
              Top = 15
              Width = 88
              Height = 22
              Hint = ''
              Caption = 'Redefinir'
              TabOrder = 1
              OnClick = btnRedefinirDescricaoClick
              Align = alNone
            end
          end
          object d7: TUniDSAFlexPanel
            Left = 482
            Top = 22
            Width = 1
            Height = 35
            Hint = ''
            TabOrder = 7
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Visible = False
            Align = alNone
          end
        end
      end
      object ugbPesquisa: TUniDSAFlexPanel
        Left = 20
        Top = 355
        Width = 716
        Height = 70
        Hint = ''
        TabOrder = 3
        Tag = 100
        Flex.AutoHeight = True
        Flex.Gap = 16
        Flex.AlignContent = faStart
        Flex.Overflow = foVisible
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        FlexItem.Shrink = 0
        ParentColor = False
        Color = clWhite
        Flex.Padding = 20
        Align = alNone
        object lblSectionugbPesquisa: TUniLabel
          Tag = 100
          Caption = 'Pesquisa'
          Height = 28
          Align = alNone
        end
        object UniContainerPanel20: TUniDSAFlexPanel
          Left = 2
          Top = 20
          Width = 712
          Height = 42
          Hint = ''
          TabOrder = 1
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object e1: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 163
            Height = 39
            Hint = ''
            TabOrder = 1
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel16: TUniLabel
              Left = 0
              Top = 0
              Width = 88
              Height = 13
              Hint = ''
              Caption = 'Valor Pesquisado'
              TabOrder = 1
              Align = alNone
            end
            object edtMenuValorPesquisado: TUniEdit
              Left = 0
              Top = 17
              Width = 163
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object e2: TUniDSAFlexPanel
            Left = 172
            Top = 0
            Width = 157
            Height = 39
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel15: TUniLabel
              Left = 0
              Top = 0
              Width = 124
              Height = 13
              Hint = ''
              Caption = ' TextPrompt/PlaceHolder'
              TabOrder = 1
              Align = alNone
            end
            object edtMenuTextPrompt: TUniEdit
              Left = 0
              Top = 17
              Width = 157
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object e3: TUniDSAFlexPanel
            Left = 335
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 4
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMenuTextPrompt: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnMenuTextPromptClick
              Align = alNone
            end
          end
          object e4: TUniDSAFlexPanel
            Left = 402
            Top = 0
            Width = 97
            Height = 39
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object ckbMenuPesquisaAutoCompletar: TUniCheckBox
              Left = 0
              Top = 22
              Width = 97
              Height = 17
              Hint = ''
              Caption = 'Auto completar'
              TabOrder = 1
              OnClick = ckbMenuPesquisaAutoCompletarClick
              Align = alNone
            end
          end
          object e5: TUniDSAFlexPanel
            Left = 505
            Top = 0
            Width = 79
            Height = 39
            Hint = ''
            TabOrder = 5
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMenuPesquisaFoco: TUniButton
              Left = 0
              Top = 17
              Width = 79
              Height = 22
              Hint = ''
              Caption = 'Foco'
              TabOrder = 1
              OnClick = btnMenuPesquisaFocoClick
              Align = alNone
            end
          end
        end
      end
      object ugbLogo: TUniDSAFlexPanel
        Left = 20
        Top = 435
        Width = 716
        Height = 70
        Hint = ''
        TabOrder = 4
        Tag = 100
        Flex.AutoHeight = True
        Flex.Gap = 16
        Flex.AlignContent = faStart
        Flex.Overflow = foVisible
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        FlexItem.Shrink = 0
        ParentColor = False
        Color = clWhite
        Flex.Padding = 20
        Align = alNone
        object lblSectionugbLogo: TUniLabel
          Tag = 100
          Caption = 'Logo'
          Height = 28
          Align = alNone
        end
        object UniContainerPanel14: TUniDSAFlexPanel
          Left = 2
          Top = 20
          Width = 712
          Height = 42
          Hint = ''
          TabOrder = 1
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object f1: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 163
            Height = 39
            Hint = ''
            TabOrder = 1
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel13: TUniLabel
              Left = 0
              Top = 0
              Width = 40
              Height = 13
              Hint = ''
              Caption = 'Imagem'
              TabOrder = 1
              Align = alNone
            end
            object edtMenuImagem: TUniEdit
              Left = 0
              Top = 17
              Width = 163
              Hint = ''
              Text = 'https://avatars.githubusercontent.com/u/16405987?s=200&v=4'
              TabOrder = 2
              Align = alNone
            end
          end
          object f2: TUniDSAFlexPanel
            Left = 172
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMudarImagem: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnMudarImagemClick
              Align = alNone
            end
          end
          object f3: TUniDSAFlexPanel
            Left = 239
            Top = 0
            Width = 163
            Height = 39
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel14: TUniLabel
              Left = 0
              Top = 0
              Width = 43
              Height = 13
              Hint = ''
              Caption = 'Empresa'
              TabOrder = 1
              Align = alNone
            end
            object edtMenuEmpresa: TUniEdit
              Left = 0
              Top = 17
              Width = 163
              Hint = ''
              Text = 'Embarcadero'
              TabOrder = 2
              Align = alNone
            end
          end
          object f4: TUniDSAFlexPanel
            Left = 408
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 4
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniButton1: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = UniButton1Click
              Align = alNone
            end
          end
          object f5: TUniDSAFlexPanel
            Left = 496
            Top = 0
            Width = 88
            Height = 39
            Hint = ''
            TabOrder = 5
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object edtMenuLogoRedefinir: TUniButton
              Left = 0
              Top = 17
              Width = 88
              Height = 22
              Hint = ''
              Caption = 'Redefinir'
              TabOrder = 1
              OnClick = edtMenuLogoRedefinirClick
              Align = alNone
            end
          end
          object f6: TUniDSAFlexPanel
            Left = 482
            Top = 5
            Width = 1
            Height = 37
            Hint = ''
            TabOrder = 6
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Visible = False
            Align = alNone
          end
        end
      end
      object ugbPerfil: TUniDSAFlexPanel
        Left = 20
        Top = 515
        Width = 716
        Height = 70
        Hint = ''
        TabOrder = 5
        Tag = 100
        Flex.AutoHeight = True
        Flex.Gap = 16
        Flex.AlignContent = faStart
        Flex.Overflow = foVisible
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        FlexItem.Shrink = 0
        ParentColor = False
        Color = clWhite
        Flex.Padding = 20
        Align = alNone
        object lblSectionugbPerfil: TUniLabel
          Tag = 100
          Caption = 'Perfil'
          Height = 28
          Align = alNone
        end
        object UniContainerPanel27: TUniDSAFlexPanel
          Left = 2
          Top = 20
          Width = 712
          Height = 42
          Hint = ''
          TabOrder = 1
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object g1: TUniDSAFlexPanel
            Left = 3
            Top = 0
            Width = 118
            Height = 39
            Hint = ''
            TabOrder = 1
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel20: TUniLabel
              Left = 0
              Top = 0
              Width = 40
              Height = 13
              Hint = ''
              Caption = 'Imagem'
              TabOrder = 1
              Align = alNone
            end
            object edtMenuImagemPerfil: TUniEdit
              Left = 0
              Top = 17
              Width = 118
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object g2: TUniDSAFlexPanel
            Left = 127
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 2
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMenuImagemPerfil: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnMenuImagemPerfilClick
              Align = alNone
            end
          end
          object g3: TUniDSAFlexPanel
            Left = 194
            Top = 0
            Width = 110
            Height = 39
            Hint = ''
            TabOrder = 3
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel18: TUniLabel
              Left = 0
              Top = 0
              Width = 30
              Height = 13
              Hint = ''
              Caption = 'Nome'
              TabOrder = 1
              Align = alNone
            end
            object edtMenuNomePerfil: TUniEdit
              Left = 0
              Top = 17
              Width = 110
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object g4: TUniDSAFlexPanel
            Left = 310
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 4
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMenuNomePerfil: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnMenuNomePerfilClick
              Align = alNone
            end
          end
          object g5: TUniDSAFlexPanel
            Left = 377
            Top = 0
            Width = 140
            Height = 39
            Hint = ''
            TabOrder = 5
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object UniLabel21: TUniLabel
              Left = 0
              Top = 0
              Width = 59
              Height = 13
              Hint = ''
              Caption = 'Sobrenome'
              ParentColor = False
              Color = clBtnFace
              TabOrder = 1
              Align = alNone
            end
            object edtMenuEmailPerfil: TUniEdit
              Left = 0
              Top = 17
              Width = 140
              Hint = ''
              Text = ''
              TabOrder = 2
              Align = alNone
            end
          end
          object g6: TUniDSAFlexPanel
            Left = 523
            Top = 0
            Width = 61
            Height = 39
            Hint = ''
            TabOrder = 6
            Tag = 102
            Flex.AutoHeight = True
            Flex.Gap = 10
            Flex.AlignContent = faStart
            Flex.Overflow = foVisible
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            FlexItem.Shrink = 0
            ParentColor = False
            Color = 16579066
            Align = alNone
            object btnMenuEmailPerfil: TUniButton
              Left = 0
              Top = 17
              Width = 61
              Height = 22
              Hint = ''
              Caption = 'Mudar'
              TabOrder = 1
              OnClick = btnMenuEmailPerfilClick
              Align = alNone
            end
          end
        end
      end
      object ugbMenu: TUniDSAFlexPanel
        Left = 20
        Top = 595
        Width = 716
        Height = 70
        Hint = ''
        TabOrder = 6
        Tag = 100
        Flex.AutoHeight = True
        Flex.Gap = 16
        Flex.AlignContent = faStart
        Flex.Overflow = foVisible
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        FlexItem.Shrink = 0
        ParentColor = False
        Color = clWhite
        Flex.Padding = 20
        Align = alNone
        object lblSectionugbMenu: TUniLabel
          Tag = 100
          Caption = 'Menu'
          Height = 28
          Align = alNone
        end
        object UniContainerPanel40: TUniDSAFlexPanel
          Left = 2
          Top = 20
          Width = 712
          Height = 38
          Hint = ''
          TabOrder = 1
          Tag = 101
          Flex.AutoHeight = True
          Flex.Gap = 10
          Flex.AlignContent = faStart
          Flex.Overflow = foVisible
          Flex.Direction = fdRow
          Flex.Wrap = fwWrap
          FlexItem.Shrink = 0
          ParentColor = False
          Color = 16579066
          Align = alNone
          object btnMenuPadrao: TUniButton
            Left = 0
            Top = 0
            Width = 134
            Height = 38
            Hint = ''
            Caption = 'Padr'#227'o'
            TabOrder = 1
            OnClick = btnMenuPadraoClick
            Align = alNone
          end
          object btnMenuAdministrativo: TUniButton
            Left = 139
            Top = 0
            Width = 134
            Height = 38
            Hint = ''
            Caption = 'Administrativo'
            TabOrder = 2
            OnClick = btnMenuAdministrativoClick
            Align = alNone
          end
          object btnSeparador: TUniButton
            Left = 278
            Top = 0
            Width = 134
            Height = 38
            Hint = ''
            Caption = 'Separador'
            TabOrder = 3
            OnClick = btnSeparadorClick
            Align = alNone
          end
          object btnNotificacoes: TUniButton
            Left = 417
            Top = 0
            Width = 134
            Height = 38
            Hint = ''
            Enabled = False
            Caption = 'Notifica'#231#245'es'
            TabOrder = 4
            OnClick = btnNotificacoesClick
            Align = alNone
          end
        end
      end
    end
  end
  object TimeTema: TUniTimer
    Interval = 100
    Enabled = False
    ClientEvent.Strings = (
      'function(sender)'
      '{'
      ' '
      '}')
    OnTimer = TimeTemaTimer
    Left = 432
    Top = 24
  end
end
