object FrLeitorQrCode: TFrLeitorQrCode
  Left = 0
  Top = 0
  Width = 640
  Height = 639
  TabOrder = 0
  object flexDemoPage: TUniDSAFlexPanel
    Tag = 120
    Left = 0
    Top = 0
    Width = 640
    Height = 639
    Hint = ''
    Flex.Direction = fdColumn
    Flex.Wrap = fwNoWrap
    Flex.Gap = 20
    Flex.Padding = 24
    Flex.Overflow = foAuto
    FlexItem.Basis = 'auto'
    Responsive.XS.Span = 12
    FlexItems = <>
    Align = alClient
    ParentColor = False
    Color = clBtnFace
    TabOrder = 0
    object usbPrincipal: TUniDSAFlexPanel
      Tag = 110
      Left = 24
      Top = 24
      Width = 592
      Height = 584
      Hint = ''
      Flex.Direction = fdColumn
      Flex.Wrap = fwNoWrap
      Flex.AlignContent = faStart
      Flex.Gap = 10
      Flex.AutoHeight = True
      FlexItem.Shrink = 0
      FlexItem.Basis = 'auto'
      Responsive.XS.Span = 12
      FlexItems = <>
      ParentColor = False
      Color = 16579066
      TabOrder = 0
      object UniLabel1: TUniLabel
        Left = 0
        Top = 0
        Width = 147
        Height = 30
        Hint = ''
        Caption = 'QrCode Reader'
        ParentFont = False
        Font.Height = 30
        Font.Style = [fsBold]
        ParentColor = False
        Color = clBtnFace
        TabOrder = 1
      end
      object UniLabel2: TUniLabel
        Left = 0
        Top = 40
        Width = 377
        Height = 20
        Hint = ''
        Caption = 'Componente para leitura de c'#243'digos de barras e QrCode'
        ParentFont = False
        Font.Color = clGray
        Font.Height = -15
        ParentColor = False
        Color = clBtnFace
        TabOrder = 2
      end
      object ugbMensagem: TUniDSAFlexPanel
        Tag = 100
        Left = 0
        Top = 70
        Width = 592
        Height = 514
        Hint = ''
        Flex.Direction = fdColumn
        Flex.Wrap = fwNoWrap
        Flex.AlignContent = faStart
        Flex.Gap = 16
        Flex.Padding = 20
        Flex.AutoHeight = True
        FlexItem.Shrink = 0
        FlexItem.Basis = 'auto'
        Responsive.XS.Span = 12
        FlexItems = <>
        ParentColor = False
        Color = clWhite
        TabOrder = 0
        object lblSectionugbMensagem: TUniLabel
          Tag = 100
          Left = 20
          Top = 20
          Width = 35
          Height = 13
          Hint = ''
          Caption = 'Leitura'
          TabOrder = 2
        end
        object UniContainerPanel20: TUniDSAFlexPanel
          Tag = 101
          Left = 20
          Top = 49
          Width = 552
          Height = 77
          Hint = ''
          Flex.AlignContent = faStart
          Flex.Gap = 10
          Flex.AutoHeight = True
          FlexItem.Shrink = 0
          FlexItem.Basis = 'auto'
          Responsive.XS.Span = 12
          FlexItems = <>
          ParentColor = False
          Color = 16579066
          TabOrder = 1
          object UniContainerPanel23: TUniDSAFlexPanel
            Tag = 102
            Left = 0
            Top = 0
            Width = 552
            Height = 45
            Hint = ''
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            Flex.AlignContent = faStart
            Flex.Gap = 10
            Flex.AutoHeight = True
            FlexItem.Shrink = 0
            FlexItem.Basis = 'auto'
            Responsive.XS.Span = 12
            FlexItems = <>
            ParentColor = False
            Color = 16579066
            TabOrder = 1
            object UniLabel16: TUniLabel
              Left = 0
              Top = 0
              Width = 52
              Height = 13
              Hint = ''
              Caption = 'Resultado'
              ParentColor = False
              Color = clBtnFace
              TabOrder = 1
            end
            object edtResultado: TUniEdit
              Left = 0
              Top = 23
              Width = 552
              Hint = ''
              Text = ''
              TabOrder = 2
            end
          end
          object UniContainerPanel22: TUniDSAFlexPanel
            Tag = 102
            Left = 0
            Top = 55
            Width = 552
            Height = 22
            Hint = ''
            Flex.Direction = fdColumn
            Flex.Wrap = fwNoWrap
            Flex.AlignContent = faStart
            Flex.Gap = 10
            Flex.AutoHeight = True
            FlexItem.Shrink = 0
            FlexItem.Basis = 'auto'
            Responsive.XS.Span = 12
            FlexItems = <>
            ParentColor = False
            Color = 16579066
            TabOrder = 2
            object btnLeitura: TUniButton
              Left = 0
              Top = 0
              Width = 552
              Height = 22
              Hint = ''
              Caption = 'Leitura '#250'nica'
              TabOrder = 1
              OnClick = btnLeituraClick
            end
          end
        end
        object qrcLeitor: TUniDSAQrCodeReader
          Left = 20
          Top = 142
          Width = 552
          Height = 352
          Hint = ''
          Text = ''
          SingleRead = False
          QrBox = 180
          FPS = 10
          SupportedFormats.QR_CODE = True
          SupportedFormats.AZTEC = True
          SupportedFormats.CODABAR = True
          SupportedFormats.CODE_39 = True
          SupportedFormats.CODE_93 = True
          SupportedFormats.CODE_128 = True
          SupportedFormats.DATA_MATRIX = True
          SupportedFormats.MAXICODE = True
          SupportedFormats.ITF = True
          SupportedFormats.EAN_13 = True
          SupportedFormats.EAN_8 = True
          SupportedFormats.PDF_417 = True
          SupportedFormats.RSS_14 = True
          SupportedFormats.RSS_EXPANDED = True
          SupportedFormats.UPC_A = True
          SupportedFormats.UPC_E = True
          SupportedFormats.UPC_EAN_EXTENSION = True
          OnAfterReading = qrcLeitorAfterReading
        end
      end
    end
  end
  object Toast: TUniDSAToast
    Version = '1.1.0'
    Icon = Success
    ShowHideTransition = Fade
    HideAfter = 3000
    AllowToastClose = True
    Stack.Enabled = True
    Stack.Value = 5
    BgColor.Enabled = False
    BgColor.Color = clAqua
    TextColor.Enabled = False
    TextColor.Color = clAqua
    TextAlign = Left
    Position.Position = BottomRight
    Position.Custom.Left = 0
    Position.Custom.Top = 0
    Position.Custom.Right = 0
    Position.Custom.Bottom = 0
    Loader.Enabled = True
    Loader.Background = clAqua
    Left = 392
    Top = 288
  end
end
