(function(global){
  "use strict";
  var API = global.UniDSAKanban = global.UniDSAKanban || {};
  function q(root, sel){ return root.querySelector(sel); }
  function qa(root, sel){ return Array.prototype.slice.call(root.querySelectorAll(sel)); }
  function closest(el, sel){ return el && el.closest ? el.closest(sel) : null; }
  function indexOfCard(card){ var list=card.parentNode; return qa(list,'.unidsa-kanban-card').indexOf(card); }
  function announce(root,text){ var a=q(root,'.unidsa-kanban-announcer'); if(a){a.textContent=''; setTimeout(function(){a.textContent=text||'';},10);} }
  function showMessage(root,text){ var old=q(root,'.unidsa-kanban-toast'); if(old) old.remove(); if(!text) return; var box=document.createElement('div'); box.className='unidsa-kanban-toast'; box.setAttribute('role','status'); box.textContent=text; root.appendChild(box); setTimeout(function(){ if(box.parentNode) box.remove(); },3200); }
  function params(obj){ var out=[]; Object.keys(obj).forEach(function(k){ out.push(k+'='+String(obj[k] == null ? '' : obj[k])); }); return out; }
  function send(state,eventName,data){ if(typeof global.ajaxRequest==='function' && state.owner){ global.ajaxRequest(state.owner,eventName,params(data||{})); } }
  function updateCounts(root){ qa(root,'.unidsa-kanban-column').forEach(function(col){ var count=qa(col,'.unidsa-kanban-card').length,limit=parseInt(col.dataset.wipLimit||'0',10); var el=q(col,'.unidsa-kanban-count'); if(el) el.textContent=String(count); col.classList.toggle('is-at-limit',limit>0&&count>=limit); }); }
  function cardList(col){ return q(col,'.unidsa-kanban-card-list'); }
  function canDrop(card,targetCol){ if(!targetCol || targetCol.dataset.allowDrop==='0') return false; var limit=parseInt(targetCol.dataset.wipLimit||'0',10); if(limit<=0) return true; var count=qa(targetCol,'.unidsa-kanban-card').filter(function(c){return c!==card;}).length; return count<limit; }
  function insertionPoint(list,clientY,ignore){ var cards=qa(list,'.unidsa-kanban-card').filter(function(c){return c!==ignore && !c.classList.contains('is-dragging');}); var best=null,bestOffset=-Infinity; cards.forEach(function(c){ var r=c.getBoundingClientRect(); var off=clientY-r.top-r.height/2; if(off<0 && off>bestOffset){ bestOffset=off; best=c; } }); return best; }
  function placeCard(card,list,clientY){ var before=insertionPoint(list,clientY,card); if(before) list.insertBefore(card,before); else list.appendChild(card); updateCounts(closest(list,'.unidsa-kanban')); }
  function begin(state,card){ var col=closest(card,'.unidsa-kanban-column'); state.drag={card:card,sourceColumn:col.dataset.columnId,oldIndex:indexOfCard(card),committed:false}; card.classList.add('is-dragging'); card.dataset.moveState='dragging'; }
  function clearDragVisual(state){ if(!state.drag) return; state.drag.card.classList.remove('is-dragging'); delete state.drag.card.dataset.moveState; qa(state.root,'.unidsa-kanban-card-list').forEach(function(l){l.classList.remove('is-over');}); }
  function commit(state,card){ var d=state.drag; if(!d) return; var col=closest(card,'.unidsa-kanban-column'); var target=col.dataset.columnId; var ni=indexOfCard(card); d.committed=true; clearDragVisual(state); updateCounts(state.root); if(d.sourceColumn!==target || d.oldIndex!==ni){ send(state,'UniDSAKanbanCardMove',{card:card.dataset.cardId,source:d.sourceColumn,target:target,oldIndex:d.oldIndex,newIndex:ni}); announce(state.root,'Cartão movido.'); } state.drag=null; }
  function rollbackLocal(state){ var d=state.drag; if(!d) return; var list=q(state.root,'.unidsa-kanban-column[data-column-id="'+cssEscape(d.sourceColumn)+'"] .unidsa-kanban-card-list'); if(list){ var cards=qa(list,'.unidsa-kanban-card'); var ref=cards[d.oldIndex]||null; if(ref) list.insertBefore(d.card,ref); else list.appendChild(d.card); } clearDragVisual(state); updateCounts(state.root); state.drag=null; }
  function cssEscape(v){ if(global.CSS && CSS.escape) return CSS.escape(v); return String(v).replace(/["\\]/g,'\\$&'); }
  API.init=function(rootId,owner,options){
    var root=document.getElementById(rootId); if(!root) return;
    var state={root:root,owner:owner,options:options||{},drag:null,keyDrag:null,touch:null}; root._uniDSAKanban=state;
    root.addEventListener('click',function(e){ var card=closest(e.target,'.unidsa-kanban-card'); if(!card || !root.contains(card) || closest(e.target,'.unidsa-kanban-drag-handle')) return; if(card.dataset.clickable==='1') send(state,'UniDSAKanbanCardClick',{card:card.dataset.cardId}); });
    root.addEventListener('dragstart',function(e){ var card=closest(e.target,'.unidsa-kanban-card'); if(!card || card.dataset.draggable==='0' || state.options.readOnly) { if(card) e.preventDefault(); return; } begin(state,card); try{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',card.dataset.cardId);}catch(_){ } });
    root.addEventListener('dragover',function(e){ if(!state.drag) return; var list=closest(e.target,'.unidsa-kanban-card-list'); if(!list) return; var col=closest(list,'.unidsa-kanban-column'); if(!canDrop(state.drag.card,col)) return; e.preventDefault(); try{e.dataTransfer.dropEffect='move';}catch(_){ } qa(root,'.unidsa-kanban-card-list').forEach(function(x){x.classList.remove('is-over');}); list.classList.add('is-over'); placeCard(state.drag.card,list,e.clientY); });
    root.addEventListener('drop',function(e){ if(!state.drag) return; e.preventDefault(); var col=closest(state.drag.card,'.unidsa-kanban-column'); if(!canDrop(state.drag.card,col)){ showMessage(root,state.options.wipMessage||'Limite da coluna atingido.'); rollbackLocal(state); return; } commit(state,state.drag.card); });
    root.addEventListener('dragend',function(){ if(state.drag && !state.drag.committed) rollbackLocal(state); });
    root.addEventListener('keydown',function(e){ var card=closest(e.target,'.unidsa-kanban-card'); if(!card) return; if(e.key==='Enter' && card.dataset.clickable==='1'){ e.preventDefault(); send(state,'UniDSAKanbanCardClick',{card:card.dataset.cardId}); return; } if(card.dataset.draggable==='0' || state.options.readOnly) return; if(e.key===' '){ e.preventDefault(); if(!state.keyDrag){ var col=closest(card,'.unidsa-kanban-column'); state.keyDrag={card:card,sourceColumn:col.dataset.columnId,oldIndex:indexOfCard(card)}; card.classList.add('is-keyboard-grabbed');card.dataset.moveState='keyboard';announce(root,'Cartão selecionado para mover. Use as setas.'); } else if(state.keyDrag.card===card){ var kd=state.keyDrag; card.classList.remove('is-keyboard-grabbed');delete card.dataset.moveState; state.drag={card:card,sourceColumn:kd.sourceColumn,oldIndex:kd.oldIndex,committed:false}; state.keyDrag=null; commit(state,card); card.focus(); } return; }
      if(!state.keyDrag || state.keyDrag.card!==card) return;
      if(e.key==='Escape'){ e.preventDefault(); state.drag={card:card,sourceColumn:state.keyDrag.sourceColumn,oldIndex:state.keyDrag.oldIndex,committed:false}; state.keyDrag=null; rollbackLocal(state); card.classList.remove('is-keyboard-grabbed');card.focus();announce(root,'Movimentação cancelada.');return; }
      var list=card.parentNode, col=closest(card,'.unidsa-kanban-column');
      if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();var cards=qa(list,'.unidsa-kanban-card'),i=cards.indexOf(card),j=e.key==='ArrowUp'?i-1:i+1;if(j>=0&&j<cards.length){if(j<i)list.insertBefore(card,cards[j]);else list.insertBefore(card,cards[j].nextSibling);updateCounts(root);card.focus();}return;}
      if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();var cols=qa(root,'.unidsa-kanban-column'),ci=cols.indexOf(col),ti=e.key==='ArrowLeft'?ci-1:ci+1;if(ti>=0&&ti<cols.length&&canDrop(card,cols[ti])){cardList(cols[ti]).appendChild(card);updateCounts(root);card.focus();}return;}
    });
    root.addEventListener('pointerdown',function(e){ if(e.pointerType==='mouse' || state.options.readOnly) return; var handle=closest(e.target,'.unidsa-kanban-drag-handle'); if(!handle) return; var card=closest(handle,'.unidsa-kanban-card'); if(!card || card.dataset.draggable==='0') return; state.touch={pointerId:e.pointerId,card:card,x:e.clientX,y:e.clientY,started:false,ghost:null}; try{handle.setPointerCapture(e.pointerId);}catch(_){ } });
    root.addEventListener('pointermove',function(e){ var t=state.touch;if(!t||t.pointerId!==e.pointerId)return;var dx=e.clientX-t.x,dy=e.clientY-t.y;if(!t.started&&Math.sqrt(dx*dx+dy*dy)<8)return;e.preventDefault();if(!t.started){t.started=true;begin(state,t.card);t.ghost=t.card.cloneNode(true);t.ghost.classList.add('unidsa-kanban-touch-ghost');t.ghost.classList.remove('is-dragging');document.body.appendChild(t.ghost);} if(t.ghost){t.ghost.style.left=(e.clientX+12)+'px';t.ghost.style.top=(e.clientY+12)+'px';} var el=document.elementFromPoint(e.clientX,e.clientY),list=closest(el,'.unidsa-kanban-card-list');if(list){var col=closest(list,'.unidsa-kanban-column');if(canDrop(t.card,col)){placeCard(t.card,list,e.clientY);qa(root,'.unidsa-kanban-card-list').forEach(function(x){x.classList.toggle('is-over',x===list);});}} });
    function touchEnd(e){var t=state.touch;if(!t||t.pointerId!==e.pointerId)return;if(t.ghost&&t.ghost.parentNode)t.ghost.remove();if(t.started&&state.drag){var col=closest(t.card,'.unidsa-kanban-column');if(canDrop(t.card,col))commit(state,t.card);else{showMessage(root,state.options.wipMessage||'Limite da coluna atingido.');rollbackLocal(state);}}state.touch=null;}
    root.addEventListener('pointerup',touchEnd);root.addEventListener('pointercancel',touchEnd);
    updateCounts(root);
  };
  API.rollback=function(rootId,cardId,columnId,index,message){ var root=document.getElementById(rootId);if(!root)return;var card=q(root,'.unidsa-kanban-card[data-card-id="'+cssEscape(cardId)+'"]');var list=q(root,'.unidsa-kanban-column[data-column-id="'+cssEscape(columnId)+'"] .unidsa-kanban-card-list');if(card&&list){var cards=qa(list,'.unidsa-kanban-card');var ref=cards[Math.max(0,Math.min(parseInt(index,10)||0,cards.length))]||null;if(ref)list.insertBefore(card,ref);else list.appendChild(card);updateCounts(root);card.focus();}showMessage(root,message||'Movimentação não permitida.');announce(root,message||'Movimentação não permitida.'); };
})(window);
